name: Deploy to AWS ECR and Terraform

on:
  push:
    branches: [main]
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

         # 2. Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

       # 7. Build and Push Docker images to ECR
    - name: Build and Push Docker images to ECR
      run: |
        if [ -d "./cloudguru-home-task/Docker/backend" ]; then
          docker build -t my-backend ./cloudguru-home-task/Docker/backend
          docker tag my-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/backend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/backend:latest
        else
          echo "Backend directory not found. Skipping backend image build."
        fi

        if [ -d "./cloudguru-home-task/Docker/frontend" ]; then
          docker build -t my-frontend ./cloudguru-home-task/Docker/frontend
          docker tag my-frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/frontend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/frontend:latest
        else
          echo "Frontend directory not found. Skipping frontend image build."
        fi

 

    # 3. Debug - Show contents of terraform folder
    - name: Debug - Show contents of terraform folder
      run: ls -la ./cloudguru-home-task/terraform

    # 4. Set up Terraform
    - name: Terraform Init
      working-directory: ./cloudguru-home-task/terraform
      run: terraform init

    # 5. Validate Terraform configuration
    - name: Terraform Plan
      working-directory: ./cloudguru-home-task/terraform
      run: terraform plan

    # 6. Apply Terraform changes
    - name: Terraform Apply
      working-directory: ./cloudguru-home-task/terraform
      run: terraform apply -auto-approve


    # 8. Deploy to ECS (zero-downtime deployment)
    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster my-cluster \
          --service my-service \
          --force-new-deployment












